name: Reusable mdBook build

on:
  workflow_call:

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    env:
      CAMLLIB: /usr/lib/x86_64-linux-gnu/ocaml/5.3.0
    steps:
      - name: Get OCaml
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ocaml
          version: 1.0
      - name: Download catala
        uses: wei/wget@v1
        with:
          args: https://github.com/CatalaLang/catala/releases/download/1.0.0/catala_1.0.0_amd64.deb -O catala.deb
      - name: Install catala
        run: sudo dpkg -i --force-all ./catala.deb
      - uses: actions/checkout@v4
      - name: Check SUMMARY structure consistency
        run: python3 scripts/check_struct_consistency.py
      - name: typecheck
        run: clerk typecheck

  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.52
    steps:
      - name: Cache Cargo registry and binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-mdbook-${{ env.MDBOOK_VERSION }}
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook
          version: ${{ env.MDBOOK_VERSION }}
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-mermaid
          version: 0.16.2
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-toc
          version: 0.14.2
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-tocjs
          version: 0.1.4
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-linkcheck
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-cmdrun
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-treesitter
          git: https://github.com/AltGr/mdbook-treesitter.git
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli
      - name: Download catala
        uses: wei/wget@v1
        with:
          args: https://github.com/CatalaLang/catala/releases/download/1.0.0/catala_1.0.0_amd64.deb -O catala.deb
      - name: Install catala
        run: sudo dpkg -i ./catala.deb || true
      - uses: actions/checkout@v4
      - name: Prepare tree-sitter
        run: |
          make -C treesitter init build
      - name: Build with mdBook
        env:
          RUST_LOG: info
        run: |
          make build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdbook-site
          path: ./book/site
